// image objects
const all = [
  {title: 'Myself', medium: 'Graphite', year: '2019', file: 'portrait_myself.jpeg', type:['portrait']},
  {title: 'My Dad', medium: 'Graphite', year: '2019', file: 'portrait_mydad.jpeg', type:['portrait']},
  {title: 'Dallin', medium: 'Graphite', year: '2019', file: 'portrait_dallin.jpeg', type:['portrait']},  
  {title: 'My Brother', medium: 'Graphite', year: '2019', file: 'portrait_kuya.jpeg', type:['portrait']},
  {title: 'Tito Noah', medium: 'Graphite', year: '2019', file: 'portrait_titonoah.jpeg', type:['portrait']},
  {title: 'Colorful Self 1', medium: 'Colored pencils', year: '2019', file: 'portrait_self1.jpeg', type:['portrait']},
  {title: 'Colorful Self 2', medium: 'Colored pencils', year: '2019', file: 'portrait_self2.jpeg', type:['portrait']},
  {title: 'Me and My Hand', medium: 'Colored pencils', year: '2019', file: 'portrait_fingers.jpeg', type:['portrait']},
  {title: 'Sofie with Her Hand', medium: 'Colored pencils', year: '2019', file: 'portrait_sofie.jpeg', type:['portrait']},
  {title: 'The Back of You', medium: 'Colored pencils', year: '2019', file: 'portrait_backofyou.jpeg', type:['portrait']},
  {title: 'Poem', medium: 'Linocut Print', year: '2018', file: 'text_alottolose.jpeg', type:['text']},
  {title: 'You Did It', medium: 'Lithograph', year: '2019', file: 'text_justlook.jpeg', type:['text']},
  {title: 'You Did It', medium: 'Lithograph', year: '2019', file: 'text_justlook2.jpeg', type:['text']},
  {title: 'Goodnite', medium: 'Ink', year: '2019', file: 'goodnite.jpg', type:['text']},
  {title: 'Because You Said Wait', medium: 'Ink and acrylic on tissue paper', year: '2019', file: 'text_because.jpeg', type:['text']},
  {title: 'Because You Said Wait', medium: 'Ink and acrylic on tissue paper', year: '2019', file: 'text_because2.jpeg', type:['text']},
  {title: 'Because You Said Wait', medium: 'Ink and acrylic on tissue paper', year: '2019', file: 'text_because3.jpeg', type:['text']},
  {title: 'Anything You Want (Until)', medium: 'Ink on tissue paper', year: '2019', file: 'text_anything.jpeg', type:['text']},
  {title: 'Anything You Want (Until)', medium: 'Ink on tissue paper', year: '2019', file: 'text_anything2.jpeg', type:['text']},
  {title: 'Anything You Want (Until)', medium: 'Ink on tissue paper', year: '2019', file: 'text_anything3.jpeg', type:['text']},
  {title: 'Dear Dream Kiss', medium: 'Ink and colored pencils', year: '2019', file: 'text_dear.jpeg', type:['text']},
  {title: 'Dear Dream Kiss', medium: 'Ink and colored pencils', year: '2019', file: 'text_dear2.jpeg', type:['text']},
  {title: 'Thanks I Won\'t Forget', medium: 'Ink, yarn, and colored pencils', year: '2019', file: 'text_thanks.jpeg', type:['text']},
  {title: 'Thanks I Won\'t Forget', medium: 'Ink, yarn, and colored pencils', year: '2019', file: 'text_thanks2.jpeg', type:['text']},
  {title: 'Thanks I Won\'t Forget', medium: 'Ink, yarn, and colored pencils', year: '2019', file: 'text_thanks3.jpeg', type:['text']},
  {title: 'New Ways', medium: 'Ink, graphite, acrylic, and pen', year: '2019', file: 'text_newways.jpeg', type:['text']},
  {title: 'New Ways', medium: 'Ink, graphite, acrylic, and pen', year: '2019', file: 'text_newways2.jpeg', type:['text']},
  {title: 'I have not yelled', medium: 'Ink, acrylic, colored pencils, and pen', year: '2019', file: 'text_fivemonths.jpeg', type:['text']},
  {title: 'I have not yelled', medium: 'Ink, acrylic, colored pencils, and pen', year: '2019', file: 'text_fivemonths2.jpeg', type:['text']},
  {title: '', medium: '', year: '2019', file: 'journal_abigail.jpeg', type:['journal']},
  {title: '', medium: '', year: '2019', file: 'journal_trampoline.jpeg', type:['journal']},
  {title: '', medium: '', year: '2019', file: 'journal_running.jpeg', type:['journal']},
  {title: '', medium: '', year: '2019', file: 'journal_cry.jpeg', type:['journal']},
  {title: '', medium: '', year: '2019', file: 'journal_umean.jpeg', type:['journal']},
  {title: '', medium: '', year: '2019', file: 'journal_myjesus.jpeg', type:['journal']},
  {title: '', medium: '', year: '2019', file: 'journal_stinkypaws.jpeg', type:['journal']},
  {title: '', medium: '', year: '2019', file: 'journal_cowsaid.jpeg', type:['journal']},
  {title: '', medium: '', year: '2019', file: 'journal_burger.jpeg', type:['journal']},
  {title: '', medium: '', year: '2019', file: 'journal_bahay.jpeg', type:['journal']},
]

export default all;