// image objects
const all = [
  {
    title: 'My Favorite Sweet',
    medium: 'Salt Dough',
    year: '2021',
    file: 'sculpture_myfavorite.jpeg',
    type: 'sculpture',
  },
  {
    title: 'Ballerina Cookie',
    medium: 'Salt Dough',
    year: '2021',
    file: 'sculpture_ballerina.jpeg',
    type: 'sculpture',
  },
  {
    title: 'Delicate (Courting Gift)',
    medium: 'Salt Dough',
    year: '2021',
    file: 'sculpture_delicate.jpeg',
    type: 'sculpture',
  },
  {
    title: 'Delicate (Courting Gift)',
    medium: 'Salt Dough',
    year: '2021',
    file: 'sculpture_delicate2.jpeg',
    type: 'sculpture',
  },
  {
    title: 'Mortar and Pestle',
    medium: 'Salt Dough',
    year: '2021',
    file: 'sculpture_mortar.jpeg',
    type: 'sculpture',
  },
  {
    title: 'Sparkle (NOT BODY SAFE - Private Collection)',
    medium: 'Salt Dough',
    year: '2021',
    file: 'sculpture_sparkle.jpeg',
    type: 'sculpture',
  },
  {
    title: 'Sparkle (NOT BODY SAFE - Private Collection)',
    medium: 'Salt Dough',
    year: '2021',
    file: 'sculpture_sparkle2.jpeg',
    type: 'sculpture',
  },
  {
    title: 'Sparkle (NOT BODY SAFE - Private Collection)',
    medium: 'Salt Dough',
    year: '2021',
    file: 'sculpture_sparkle3.jpeg',
    type: 'sculpture',
  },
  {
    title: 'My Toy (NOT BODY SAFE - Private Collection)',
    medium: 'Salt Dough',
    year: '2021',
    file: 'sculpture_mytoy.jpeg',
    type: 'sculpture',
  },
  {
    title: 'My Toy (NOT BODY SAFE - Private Collection)',
    medium: 'Salt Dough',
    year: '2021',
    file: 'sculpture_mytoy2.jpeg',
    type: 'sculpture',
  },
  {
    title: 'My Toy (NOT BODY SAFE - Private Collection)',
    medium: 'Salt Dough',
    year: '2021',
    file: 'sculpture_mytoy3.jpeg',
    type: 'sculpture',
  },
  {
    title: 'Gold Luck, Be Safe!',
    medium: 'Salt Dough',
    year: '2021',
    file: 'sculpture_goldluck.jpeg',
    type: 'sculpture',
  },
  {
    title: 'Gold Luck, Be Safe!',
    medium: 'Salt Dough',
    year: '2021',
    file: 'sculpture_goldluck2.jpeg',
    type: 'sculpture',
  },
  {
    title: 'Birdlike',
    medium: 'Salt Dough',
    year: '2021',
    file: 'sculpture_birdlike.jpeg',
    type: 'sculpture',
  },
  {
    title: 'Devilish',
    medium: 'Salt Dough',
    year: '2021',
    file: 'sculpture_devilish.jpeg',
    type: 'sculpture',
  },
  {
    title: 'A Man of His Word',
    medium: 'Salt Dough',
    year: '2021',
    file: 'sculpture_manofhisword.jpeg',
    type: 'sculpture',
  },
  {
    title: 'A Man of His Word',
    medium: 'Salt Dough',
    year: '2021',
    file: 'sculpture_manofhisword2.jpeg',
    type: 'sculpture',
  },
  {
    title: 'Merry',
    medium: 'Salt Dough',
    year: '2021',
    file: 'sculpture_merry.jpeg',
    type: 'sculpture',
  },
  {
    title: 'Pinwheel',
    medium: 'Salt Dough',
    year: '2021',
    file: 'sculpture_pinwheel.jpeg',
    type: 'sculpture',
  },
  {
    title: 'Puppy Dog (I want you!)',
    medium: 'Modeling Clay',
    year: '2021',
    file: 'sculpture_puppydog.jpeg',
    type: 'sculpture',
  },
  {
    title: 'Puppy Dog (I want you!)',
    medium: 'Modeling Clay',
    year: '2021',
    file: 'sculpture_puppydog2.jpeg',
    type: 'sculpture',
  },
  {
    title: 'Myself',
    medium: 'Graphite',
    year: '2019',
    file: 'portrait_myself.jpeg',
    type: 'portraits',
  },
  {
    title: 'My Dad',
    medium: 'Graphite',
    year: '2019',
    file: 'portrait_mydad.jpeg',
    type: 'portraits',
  },
  {
    title: 'Elaine',
    medium: 'Graphite',
    year: '2019',
    file: 'portrait_elaine.jpeg',
    type: 'portraits',
  },
  {
    title: 'My Brother',
    medium: 'Graphite',
    year: '2019',
    file: 'portrait_kuya.jpeg',
    type: 'portraits',
  },
  {
    title: 'Tito Noah',
    medium: 'Graphite',
    year: '2019',
    file: 'portrait_titonoah.jpeg',
    type: 'portraits',
  },
  {
    title: 'Colorful Self 1',
    medium: 'Colored pencils',
    year: '2019',
    file: 'portrait_self1.jpeg',
    type: 'portraits',
  },
  {
    title: 'Colorful Self 2',
    medium: 'Colored pencils',
    year: '2019',
    file: 'portrait_self2.jpeg',
    type: 'portraits',
  },
  {
    title: 'Me and My Hand',
    medium: 'Colored pencils',
    year: '2019',
    file: 'portrait_fingers.jpeg',
    type: 'portraits',
  },
  {
    title: 'Sofie with Her Hand',
    medium: 'Colored pencils',
    year: '2019',
    file: 'portrait_sofie.jpeg',
    type: 'portraits',
  },
  {
    title: 'The Back of You',
    medium: 'Colored pencils',
    year: '2019',
    file: 'portrait_backofyou.jpeg',
    type: 'portraits',
  },
  {
    title: 'Poem',
    medium: 'Linocut Print',
    year: '2018',
    file: 'text_alottolose.jpeg',
    type: 'text',
  },
  {
    title: 'You Did It',
    medium: 'Lithograph',
    year: '2019',
    file: 'text_justlook.jpeg',
    type: 'text',
  },
  {
    title: 'You Did It',
    medium: 'Lithograph',
    year: '2019',
    file: 'text_justlook2.jpeg',
    type: 'text',
  },
  {
    title: 'Goodnite',
    medium: 'Ink',
    year: '2019',
    file: 'goodnite.jpg',
    type: 'text',
  },
  {
    title: 'Because You Said Wait',
    medium: 'Ink and acrylic on tissue paper',
    year: '2019',
    file: 'text_because.jpeg',
    type: 'text',
  },
  {
    title: 'Because You Said Wait',
    medium: 'Ink and acrylic on tissue paper',
    year: '2019',
    file: 'text_because2.jpeg',
    type: 'text',
  },
  {
    title: 'Because You Said Wait',
    medium: 'Ink and acrylic on tissue paper',
    year: '2019',
    file: 'text_because3.jpeg',
    type: 'text',
  },
  {
    title: 'Anything You Want (Until)',
    medium: 'Ink on tissue paper',
    year: '2019',
    file: 'text_anything.jpeg',
    type: 'text',
  },
  {
    title: 'Anything You Want (Until)',
    medium: 'Ink on tissue paper',
    year: '2019',
    file: 'text_anything2.jpeg',
    type: 'text',
  },
  {
    title: 'Anything You Want (Until)',
    medium: 'Ink on tissue paper',
    year: '2019',
    file: 'text_anything3.jpeg',
    type: 'text',
  },
  {
    title: 'Dear Dream Kiss',
    medium: 'Ink and colored pencils',
    year: '2019',
    file: 'text_dear.jpeg',
    type: 'text',
  },
  {
    title: 'Dear Dream Kiss',
    medium: 'Ink and colored pencils',
    year: '2019',
    file: 'text_dear2.jpeg',
    type: 'text',
  },
  {
    title: "Thanks I Won't Forget",
    medium: 'Ink, yarn, and colored pencils',
    year: '2019',
    file: 'text_thanks.jpeg',
    type: 'text',
  },
  {
    title: "Thanks I Won't Forget",
    medium: 'Ink, yarn, and colored pencils',
    year: '2019',
    file: 'text_thanks2.jpeg',
    type: 'text',
  },
  {
    title: "Thanks I Won't Forget",
    medium: 'Ink, yarn, and colored pencils',
    year: '2019',
    file: 'text_thanks3.jpeg',
    type: 'text',
  },
  {
    title: 'New Ways',
    medium: 'Ink, graphite, acrylic, and pen',
    year: '2019',
    file: 'text_newways.jpeg',
    type: 'text',
  },
  {
    title: 'New Ways',
    medium: 'Ink, graphite, acrylic, and pen',
    year: '2019',
    file: 'text_newways2.jpeg',
    type: 'text',
  },
  {
    title: 'I have not yelled',
    medium: 'Ink, acrylic, colored pencils, and pen',
    year: '2019',
    file: 'text_fivemonths.jpeg',
    type: 'text',
  },
  {
    title: 'I have not yelled',
    medium: 'Ink, acrylic, colored pencils, and pen',
    year: '2019',
    file: 'text_fivemonths2.jpeg',
    type: 'text',
  },
  {
    title: '',
    medium: '',
    year: '2019',
    file: 'journal_abigail.jpeg',
    type: 'journals',
  },
  {
    title: '',
    medium: '',
    year: '2019',
    file: 'journal_trampoline.jpeg',
    type: 'journals',
  },
  {
    title: '',
    medium: '',
    year: '2019',
    file: 'journal_running.jpeg',
    type: 'journals',
  },
  {
    title: '',
    medium: '',
    year: '2019',
    file: 'journal_cry.jpeg',
    type: 'journals',
  },
  {
    title: '',
    medium: '',
    year: '2019',
    file: 'journal_umean.jpeg',
    type: 'journals',
  },
  {
    title: '',
    medium: '',
    year: '2019',
    file: 'journal_myjesus.jpeg',
    type: 'journals',
  },
  {
    title: '',
    medium: '',
    year: '2019',
    file: 'journal_stinkypaws.jpeg',
    type: 'journals',
  },
  {
    title: '',
    medium: '',
    year: '2019',
    file: 'journal_cowsaid.jpeg',
    type: 'journals',
  },
  {
    title: '',
    medium: '',
    year: '2019',
    file: 'journal_burger.jpeg',
    type: 'journals',
  },
  {
    title: '',
    medium: '',
    year: '2019',
    file: 'journal_bahay.jpeg',
    type: 'journals',
  },
];

export default all;
